const UPDATE_CONTENTS = "UPDATE_CONTENTS";
const UPDATE_TOTAL = "UPDATE_TOTAL";
const ADD_CONTENT = "ADD_CONTENT";
const REMOVE_CONTENT = "REMOVE_CONTENT";

export { ADD_CONTENT, REMOVE_CONTENT, UPDATE_CONTENTS, UPDATE_TOTAL };
